coramer_sigtec_backend_company_report_technical_data_storages:
    pattern:  /storages.{_format}
    defaults:
        _controller: coramer_sigtec_report_technical.controller.report_technical.generic_data:getStoragesAction
        _format: json
    options:
        expose: true
    requirements:
        _method: GET
        _format: json|xml
        
coramer_sigtec_backend_company_report_technical_data_separated_resin:
    pattern:  /separated-resin.{_format}
    defaults:
        _controller: coramer_sigtec_report_technical.controller.report_technical.generic_data:getSeparatedResinAction
        _format: json
    options:
        expose: true
    requirements:
        _method: GET
        _format: json|xml
        
coramer_sigtec_backend_company_report_technical_data_type_process:
    pattern:  /type-process.{_format}
    defaults:
        _controller: coramer_sigtec_report_technical.controller.report_technical.generic_data:getTypeProcessAction
        _format: json
    options:
        expose: true
    requirements:
        _method: GET
        _format: json|xml
        
coramer_sigtec_backend_company_report_technical_data_process:
    pattern:  /{idTypeProcess}/process.{_format}
    defaults:
        _controller: coramer_sigtec_report_technical.controller.report_technical.generic_data:getProcessAction
        _format: json
    options:
        expose: true
    requirements:
        _method: GET
        _format: json|xml
        
coramer_sigtec_backend_company_report_technical_data_resin_by_coramer:
    pattern:  /resin-by-coramer.{_format}
    defaults:
        _controller: coramer_sigtec_report_technical.controller.report_technical.generic_data:getResinByCoramerAction
        _format: json
    options:
        expose: true
    requirements:
        _method: GET
        _format: json|xml
        
coramer_sigtec_backend_company_report_technical_data_resin_not_by_coramer:
    pattern:  /resin-not-by-coramer.{_format}
    defaults:
        _controller: coramer_sigtec_report_technical.controller.report_technical.generic_data:getResinNotByCoramerAction
        _format: json
    options:
        expose: true
    requirements:
        _method: GET
        _format: json|xml
        
coramer_sigtec_backend_company_report_technical_data_grade:
    pattern:  /grades.{_format}
    defaults:
        _controller: coramer_sigtec_report_technical.controller.report_technical.generic_data:getGradeAction
        _format: json
    options:
        expose: true
    requirements:
        _method: GET
        _format: json|xml
        
coramer_sigtec_backend_company_report_technical_data_product:
    pattern:  /products.{_format}
    defaults:
        _controller: coramer_sigtec_report_technical.controller.report_technical.generic_data:getProductsAction
        _format: json
    options:
        expose: true
    requirements:
        _method: GET
        _format: json|xml
        
coramer_sigtec_backend_company_report_technical_data_additive_type_concentration:
    pattern:  /additive-used-type-concentration.{_format}
    defaults:
        _controller: coramer_sigtec_report_technical.controller.report_technical.generic_data:getAdditiveUsedTypeConcentrationAction
        _format: json
    options:
        expose: true
    requirements:
        _method: GET
        _format: json|xml
        
coramer_sigtec_backend_company_report_technical_data_additive:
    pattern:  /additives.{_format}
    defaults:
        _controller: coramer_sigtec_report_technical.controller.report_technical.generic_data:getAdditivesAction
        _format: json
    options:
        expose: true
    requirements:
        _method: GET
        _format: json|xml
        
coramer_sigtec_backend_company_report_technical_data_additive_products:
    pattern:  /additives.{_format}
    defaults:
        _controller: coramer_sigtec_report_technical.controller.report_technical.generic_data:getAdditiveProductsAction
        _format: json
    options:
        expose: true
    requirements:
        _method: GET
        _format: json|xml
        
coramer_sigtec_backend_company_report_technical_data_additive_suppliers:
    pattern:  /additives-suppliers.{_format}
    defaults:
        _controller: coramer_sigtec_report_technical.controller.report_technical.generic_data:getAdditiveSuppliersAction
        _format: json
    options:
        expose: true
    requirements:
        _method: GET
        _format: json|xml