coramer_sigtec_backend_company_report_technical_client_index:
    pattern:  /.{_format}
    defaults:
        _controller: coramer_sigtec_backend.controller.company_report_technical:indexClientAction
        _format: html
    options:
        expose: true
    requirements:
        _method: GET
        
coramer_sigtec_backend_company_report_technical_show:
    pattern:  /{id}/show.{_format}
    defaults:
        _controller: coramer_sigtec_backend.controller.company_report_technical:showAction
        _format: html
    options:
        expose: true
    requirements:
        _method: GET

coramer_sigtec_backend_company_report_technical_create:
    pattern:  /create
    defaults:
        _controller: coramer_sigtec_backend.controller.company_report_technical:createAction
    requirements:
        _method: GET|POST
        
coramer_sigtec_backend_company_report_technical_update:
    pattern:  /{id}/update
    defaults:
        _controller: coramer_sigtec_backend.controller.company_report_technical:updateAction
        _sylius:
            form: coramer_sigtec_reporttechnicalbundle_reporttechnical
    requirements:
        _method: GET|PUT
        
coramer_sigtec_backend_company_report_technical_delete:
    pattern:  /{id}/delete
    defaults:
        _controller: coramer_sigtec_backend.controller.company_report_technical:deleteAction
    requirements:
        _method: POST|DELETE
        
coramer_sigtec_backend_company_report_technical_professional_profile:
    pattern:  /{id}/professional-profile.{_format}
    defaults:
        _controller: coramer_sigtec_backend.controller.company_report_technical:getProfessionalProfileAction
        _format: json
    options:
        expose: true
    requirements:
        _method: GET
        _format: json|xml
        
coramer_sigtec_company_report_technical_data:
    resource: "@CoramerSigtecWebBundle/Resources/config/routing/backend/company/report_technical/generic_data.yml"
    prefix:   /data
    
coramer_sigtec_company_report_technical_properties:
    resource: "@CoramerSigtecWebBundle/Resources/config/routing/backend/company/report_technical/properties/description_area_company/detail_product_storage.yml"
    prefix:   /{id}/detail-product-storage
    
coramer_sigtec_company_report_technical_properties_materials:
    resource: "@CoramerSigtecWebBundle/Resources/config/routing/backend/company/report_technical/properties/description_area_company/detail_product_storage/material.yml"
    prefix:   /detail-product-storage
    
coramer_sigtec_company_report_technical_properties_production_level:
    resource: "@CoramerSigtecWebBundle/Resources/config/routing/backend/company/report_technical/properties/production_level.yml"
    prefix:   /{id}/production_level