Coramer\Sigtec\ReportTechnicalBundle\Entity\Properties\DescriptionAreaCompany\DetailProductStorage\Material:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            groups: [show,report_technical]
        description:
            expose: true
            groups: [show,report_technical]