Coramer\Sigtec\ReportTechnicalBundle\Entity\Properties\DescriptionAreaCompany:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            groups: [show,report_technical]
        plantsDescription:
            expose: true
            groups: [show,report_technical]
        detailProductStorages:
            expose: true
            groups: [show,report_technical]