Coramer\Sigtec\ReportTechnicalBundle\Entity\Master\Additive:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            groups: [id]
        description:
            expose: true
            groups: [show,list,report_technical]