Coramer\Sigtec\ReportTechnicalBundle\Entity\Master\TypeProcess:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            groups: [show,list,id]
        description:
            expose: true
            groups: [show,list,report_technical]