Coramer\Sigtec\ReportTechnicalBundle\Entity\Master\ReasonPurchase:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            groups: [id,show]
        description:
            expose: true
            groups: [show,list,report_technical]
        help:
            expose: true
            groups: [show,list,report_technical]