Coramer\Sigtec\ReportTechnicalBundle\Entity\Properties\ProductManufactured:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            groups: [show,id]
        process:
            expose: true
            groups: [show,report_technical]
        product:
            expose: true
            groups: [show,report_technical]
        grade:
            expose: true
            groups: [show,report_technical]
        requirement:
            expose: true
            groups: [show,report_technical]