Coramer\Sigtec\ReportTechnicalBundle\Entity\Properties\DescriptionAreaCompany\Area:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            groups: [show]
        descriptionArea:
            expose: true
            groups: [show]
        areas:
            expose: true
            groups: [show]
        parent:
            expose: true
            groups: [show]
        totalArea:
            expose: true
            groups: [show]
        coveredArea:
            expose: true
            groups: [show]