Coramer\Sigtec\ReportTechnicalBundle\Entity\Properties\ProductionLevel:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            groups: [show,report_technical]
        process:
            expose: true
            groups: [show,report_technical]
        shifts:
            expose: true
            groups: [show,report_technical]
        hours:
            expose: true
            groups: [show,report_technical]
        daysMonth:
            expose: true
            groups: [show,report_technical]
        theoretical:
            expose: true
            groups: [show,report_technical]
        installed:
            expose: true
            groups: [show,report_technical]
        busy:
            expose: true
            groups: [show,report_technical]
        idle:
            expose: true
            groups: [show,report_technical]
        percentage:
            expose: true
            groups: [show,report_technical]
        machineries:
            expose: true
            groups: [show,report_technical]