Coramer\Sigtec\ReportTechnicalBundle\Entity\Properties\ProductionLevel:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            groups: [show]
        process:
            expose: true
            groups: [show]
        shifts:
            expose: true
            groups: [show]
        hours:
            expose: true
            groups: [show]
        daysMonth:
            expose: true
            groups: [show]
        theoretical:
            expose: true
            groups: [show]
        installed:
            expose: true
            groups: [show]
        busy:
            expose: true
            groups: [show]
        idle:
            expose: true
            groups: [show]
        percentage:
            expose: true
            groups: [show]