Coramer\Sigtec\ReportTechnicalBundle\Entity\Properties\DescriptionAreaCompany\PlantDescription:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            groups: [show,report_technical]
        plant:
            expose: true
            groups: [show,report_technical]
        area:
            expose: true
            groups: [show,report_technical]