Coramer\Sigtec\ReportTechnicalBundle\Entity\Master\Grade:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            groups: [show,list,grade]
        description:
            expose: true
            groups: [show,list,grade]
        resin:
            expose: true
            groups: [show,grade]