Coramer\Sigtec\ReportTechnicalBundle\Entity\Master\FeatureMachinery:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            groups: [id,show]
        name:
            expose: true
            groups: [show,list,report_technical]
        description:
            expose: true
            groups: [show,list,report_technical]
        help:
            expose: true
            groups: [show,list,report_technical]
        fieldType:
            expose: true
            groups: [show,list,report_technical]