Coramer\Sigtec\ReportTechnicalBundle\Entity\Master\Resin:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            groups: [id,list,grade]
        description:
            expose: true
            groups: [show,list,grade,report_technical]
        grades:
            expose: true
            groups: [show,list]