Coramer\Sigtec\ReportTechnicalBundle\Entity\Master\Process:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            groups: [show,list,id]
        description:
            expose: true
            groups: [show,list,report_technical]
        typeProcess:
            expose: true
            groups: [show,list,report_technical]