Coramer\Sigtec\ReportTechnicalBundle\Entity\Master\Grade:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            groups: [id,show,list,grade]
        description:
            expose: true
            groups: [show,list,grade,report_technical]
        resin:
            expose: true
            groups: [show,grade,report_technical]