Coramer\Sigtec\ReportTechnicalBundle\Entity\Master\SubSegment:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            groups: [id,show,list]
        description:
            expose: true
            groups: [show,list,report_technical]