coramer_sigtec_web:
    resource: "@CoramerSigtecWebBundle/Controller/"
    type:     annotation
    prefix:   /

coramer_sigtec_core:
    resource: "@CoramerSigtecCoreBundle/Controller/"
    type:     annotation
    prefix:   /

