<?php

namespace Coramer\Sigtec\ReportTechnicalBundle\Repository;

use Tecnocreaciones\Bundle\ResourceBundle\Doctrine\ORM\EntityRepository;

/**
 * ReportTechnicalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReportTechnicalRepository extends EntityRepository
{
    
}
