<?php

namespace Coramer\Sigtec\ReportTechnicalBundle\Repository\Master;

use Tecnocreaciones\Bundle\ResourceBundle\Doctrine\ORM\EntityRepository as BaseEntityRepository;

/**
 * AdditiveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdditiveRepository extends BaseEntityRepository
{
    
}
