<?php

namespace Coramer\Sigtec\ReportTechnicalBundle\Repository\Master;

use Doctrine\ORM\EntityRepository;

/**
 * FeatureMachineryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeatureMachineryRepository extends EntityRepository
{
}
