<?php

namespace Coramer\Sigtec\ReportTechnicalBundle\Repository\Master;

use Coramer\Sigtec\CoreBundle\Repository\Model\MasterEntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends MasterEntityRepository
{
    function getQueryBuilderByReportTechnical(\Coramer\Sigtec\ReportTechnicalBundle\Entity\ReportTechnical $reportTechnical) 
    {
        $qb = $this->createQueryBuilder('p');
        $qb->select('p')
           ->innerJoin('p.productsManufactured', 'pm')
           ->andWhere('pm.reportTechnical = :reportTechnical')
           ->setParameter('reportTechnical', $reportTechnical)
        ;
        return $qb;
    }
}
