<?php

namespace Coramer\Sigtec\ReportTechnicalBundle\Repository\Master;

use Coramer\Sigtec\CoreBundle\Repository\Model\MasterEntityRepository;

/**
 * SegmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SegmentRepository extends MasterEntityRepository
{
}
