<?php

namespace Coramer\Sigtec\ReportTechnicalBundle\Repository\Master;

use Coramer\Sigtec\CoreBundle\Repository\Model\MasterEntityRepository;

/**
 * SegmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SegmentRepository extends MasterEntityRepository
{
    function getQueryBuilderByReportTechnical(\Coramer\Sigtec\ReportTechnicalBundle\Entity\ReportTechnical $reportTechnical)
    {
        $qb = $this->createQueryBuilder('s');
        $qb->innerJoin('s.descriptionMarkets', 'dm')
           ->andWhere('dm.reportTechnical = :reportTechnical')
           ->setParameter('reportTechnical',$reportTechnical)
                ;
        return $qb;
    }
    
    function getByReportTechnical(\Coramer\Sigtec\ReportTechnicalBundle\Entity\ReportTechnical $reportTechnical) 
    {
        return $this->getQueryBuilderByReportTechnical($reportTechnical)->getQuery()->getResult();
    }
}
