<?php

namespace Coramer\Sigtec\ReportTechnicalBundle\Repository\Master;

use Doctrine\ORM\EntityRepository;

/**
 * TypeProcessRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeProcessRepository extends EntityRepository
{
}
