coramer_sigtec_company_index:
    pattern:  /.{_format}
    defaults:
        _controller:  coramer_sigtec.controller.company:indexAction
        _format: html
    options:
        expose: true
coramer_sigtec_company_show:
    pattern:  /{id}/show.{_format}
    defaults: 
        _controller:  coramer_sigtec.controller.company:showAction
        _format: html

coramer_sigtec_company_create:
    pattern:  /create
    defaults:
        _controller: coramer_sigtec.controller.company:createAction
        _sylius:
            form: coramer_sigtec_companybundle_company

coramer_sigtec_company_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "CoramerSigtecCompanyBundle:Company:edit" }

coramer_sigtec_company_update:
    pattern:  /{id}/update
    defaults: { _controller: "CoramerSigtecCompanyBundle:Company:update" }
    requirements: { _method: post|put }

coramer_sigtec_company_delete:
    pattern:  /{id}/delete
    defaults: 
        _controller: coramer_sigtec.controller.company:deleteAction
    requirements: { _method: post|delete }
