imports:
    - { resource: config.yml }

framework:
    test: ~
    translator:      { fallback: "es" }
    default_locale:  "es"
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

doctrine:
    dbal:
        dbname:   "%database_name%_test"
        
liip_doctrine_cache:
    namespaces:
        sylius_settings:
            type: array
            
monolog:
    handlers:
        main:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: debug
        firephp:
            type:  firephp
            level: info

stof_doctrine_extensions:
    default_locale: es