imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
        #cookie_lifetime: 7200 # 2 hours max session
        gc_maxlifetime: 600 #10 min session inactive
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
        resources:
            - 'CoramerSigtecCoreBundle:Form:fields.html.twig'

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        ['CoramerSigtecWebBundle','FOSUserBundle','TecnocreacionesVzlaGovernmentBundle']
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        types:
            json: Sonata\Doctrine\Types\JsonType
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: "%kernel.root_dir%/data/data.db3"
        # path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        entity_managers:
            default:
                auto_mapping: true
                mappings:
                    ApplicationSonataUserBundle: ~
                    SonataUserBundle: ~
                    FOSUserBundle: ~
                    gedmo_loggable:
                        type: annotation
                        prefix: Gedmo\Loggable\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"
                        alias: GedmoLoggable # this one is optional and will default to the name set for the mapping
                        is_bundle: false
                filters:
                    softdeleteable:
                        class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                        enabled: true


# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: Application\Sonata\UserBundle\Entity\User
    registration:
        form:
            type: sigtec_user_registration
    profile:
        form:
            type: tecnocreaciones_vzla_government_user_registration
    group:
        group_class:   Application\Sonata\UserBundle\Entity\Group
        group_manager: sonata.user.orm.group_manager                    # If you're using doctrine orm (use sonata.user.mongodb.user_manager for mongodb)
    service:
        user_manager: sonata.user.orm.user_manager
        
stof_doctrine_extensions:
    default_locale: %locale%
    orm:
        default:
            tree: true
            sluggable: true
            timestampable: true
            softdeleteable: true
            loggable: true
            
liip_imagine:
    filter_sets:
        image_16x16:
            filters:
                thumbnail: { size: [16, 16], mode: outbound }
        image_220x140:
            filters:
                thumbnail: { size: [220, 140], mode: inset }
                
        image_200x25:
            filters:
                thumbnail: { size: [200, 25], mode: inset }

lunetics_locale:
    allowed_locales:
        - es
        - en
    strict_mode: true # defaults to false
    guessing_order:
        - query
        - router
        - session
        - cookie
        - browser
    switcher:
        show_current_locale: true
        
tecnocreaciones_install:
    credentials:
        email: inhack20@gmail.com
                
tecnocreaciones_tools:
    table_prefix:
        use_prefix: true
        prefix: %app.db.prefix%
    sequence_generator:
        options:
            additional_masks:
                - mask1
                - mask2
            
        
jms_serializer:
    handlers:
        datetime:
            default_format: "Y-m-d H:m:s" # ISO8601
    metadata:
        debug: "%kernel.debug%"
        auto_detection: true
        directories:
            FOSUserBundle:
                namespace_prefix: FOS\UserBundle
                path: "@CoramerSigtecCoreBundle/Resources/config/serializer/fos"
            
fos_rest:
    allowed_methods_listener: true
    routing_loader:
        default_format: json
    view:
        view_response_listener: force
        mime_types:
            # Prototype
            name: ["application/vnd.user.v1+json"]
    access_denied_listener:
        # all requests using the 'json' format will return a 403 on an access denied violation
        json: true
        
sensio_framework_extra:
    view:    { annotations: false }
    router:  { annotations: true }
    
bazinga_js_translation:
    locale_fallback: "%locale%" 

nelmio_api_doc: ~

tecnocreaciones_vzla_government:
    template:
        developer:
            app_title: SIGTEC
            menu: Coramer\Sigtec\TemplateBundle\Menu\Template\Developer\BackendMenuBuilder
            angular_dependencies: ['bundles/coramersigtecweb/angular/modules/sigtecModule.js']
            logo:
                login_watermark: 'bundles/coramersigtectemplate/template/developer/img/favicons/watermark.png'
                panel_right: 'bundles/coramersigtectemplate/template/developer/img/favicons/logo.png'
                icon_png: 'bundles/coramersigtectemplate/template/developer/img/favicons/favicon.png'
                icon_ico: 'bundles/coramersigtectemplate/template/developer/img/favicons/favicon.ico'
    config:
        main_route: 'coramer_sigtec_web_dashboard_index'

tecnocreaciones_vzla_entity:
    backend_admin: true

sonata_user:
    security_acl: true
    manager_type: orm # can be orm or mongodb
    impersonating:
        route:                coramer_sigtec_web_dashboard_index
        parameters:           { path: / }

sonata_block:
    default_contexts: [cms]
        
    blocks:
        sonata.block.service.menu:
        # Enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts:   [admin]
        sonata.admin.block.search_result:
            contexts:   [admin]
        sonata.user.block.menu:    # used to display the menu in profile pages
            contexts: [user]
        sonata.user.block.account: # used to display menu option (login option)
            contexts: [user]

sonata_admin:
    title:      SIGTEC
    title_logo: bundles/coramersigtectemplate/template/developer/img/favicons/admin_logo.png
    dashboard:
        groups:
            sonata.admin.group.administration:
                label:           sonata_administration
                label_catalogue: SonataAdminBundle
                icon:            '<i class="fa fa-cogs"></i>'
                items:
                    - sonata.user.admin.user
                    - sonata.user.admin.group
            admin.group.report_technical:
                label_catalogue: admin
                icon:            '<i class="fa fa-pencil-square-o"></i>'
            admin.group.company:
                label_catalogue: admin
                icon:            '<i class="fa fa-suitcase"></i>'
            admin.group.vzla_entity:
                label_catalogue: admin
                icon:            '<i class="fa fa-play-circle"></i>'
sylius_resource:
    resources:
         coramer_sigtec_backend.user:
            driver: doctrine/orm
            classes:
                model: Coramer\Sigtec\CoreBundle\Entity\User
         coramer_sigtec_backend.company:
            driver: doctrine/orm
            templates: CoramerSigtecWebBundle:Backend/Company
            classes:
                controller: Coramer\Sigtec\CompanyBundle\Controller\CompanyController
                model: Coramer\Sigtec\CompanyBundle\Entity\Company
         coramer_sigtec_backend.company_plant:
            driver: doctrine/orm
            templates: CoramerSigtecWebBundle:Backend/Plant
            classes:
                controller: Coramer\Sigtec\CompanyBundle\Controller\PlantController
                model: Coramer\Sigtec\CompanyBundle\Entity\Plant
         coramer_sigtec_backend.company_contact:
            driver: doctrine/orm
            templates: CoramerSigtecWebBundle:Backend/Contact
            classes:
                controller: Coramer\Sigtec\CompanyBundle\Controller\ContactController
                model: Coramer\Sigtec\CompanyBundle\Entity\Contact
         coramer_sigtec_backend.company_report_technical:
            driver: doctrine/orm
            templates: CoramerSigtecWebBundle:Backend/ReportTechnical
            classes:
                controller: Coramer\Sigtec\ReportTechnicalBundle\Controller\ReportTechnicalController
                model: Coramer\Sigtec\ReportTechnicalBundle\Entity\ReportTechnical
         coramer_sigtec_backend.company_report_technical_properties_detail_product_storage:
            driver: doctrine/orm
            templates: CoramerSigtecWebBundle:Backend/ReportTechnical/Properties/DescriptionAreaCompany
            classes:
                controller: Coramer\Sigtec\ReportTechnicalBundle\Controller\Properties\DescriptionAreaCompany\DetailProductStorageController
                model: Coramer\Sigtec\ReportTechnicalBundle\Entity\Properties\DescriptionAreaCompany\DetailProductStorage
         coramer_sigtec_backend.company_report_technical_properties_material:
            driver: doctrine/orm
            classes:
                controller: Coramer\Sigtec\ReportTechnicalBundle\Controller\Properties\DescriptionAreaCompany\DetailProductStorage\MaterialController
                model: Coramer\Sigtec\ReportTechnicalBundle\Entity\Properties\DescriptionAreaCompany\DetailProductStorage\Material
         api_tecnocreaciones_vzla_entity.country:
            driver: doctrine/orm
            classes:
                controller: Tecnocreaciones\Vzla\ApiBundle\Controller\CountryController
                model: Tecnocreaciones\Vzla\EntityBundle\Entity\Country
         api_tecnocreaciones_vzla_entity.state:
            driver: doctrine/orm
            classes:
                controller: Tecnocreaciones\Vzla\ApiBundle\Controller\StateController
                model: Tecnocreaciones\Vzla\EntityBundle\Entity\State
         api_tecnocreaciones_vzla_entity.city:
            driver: doctrine/orm
            classes:
                controller: Tecnocreaciones\Vzla\ApiBundle\Controller\CityController
                model: Tecnocreaciones\Vzla\EntityBundle\Entity\City
         api_tecnocreaciones_vzla_entity.city:
            driver: doctrine/orm
            classes:
                controller: Tecnocreaciones\Vzla\ApiBundle\Controller\RegionController
                model: Tecnocreaciones\Vzla\EntityBundle\Entity\Region