tecnocreaciones_vzla_api:
    resource: "@TecnocreacionesVzlaApiBundle/Controller/"
    type:     annotation
    prefix:   /

coramer_sigtec_company:
    resource: "@CoramerSigtecCompanyBundle/Controller/"
    type:     annotation
    prefix:   /

web_bundle:
    resource: "@CoramerSigtecWebBundle/Resources/config/routing.yml"
    requirements:
        _locale: es|en

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc
    
tecnocreaciones_vzla_api:
    resource: "@TecnocreacionesVzlaApiBundle/Resources/config/routing.yml"
    prefix:   /api
    type: rest
    
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

_bazinga_jstranslation:
    resource: "@BazingaJsTranslationBundle/Resources/config/routing/routing.yml"
    
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"