<?php

namespace Coramer\Sigtec\ReportTechnicalBundle\Repository\Properties\GrowthPotential;

use Coramer\Sigtec\CoreBundle\Repository\Model\MasterEntityRepository;

/**
 * GrowingMarketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GrowingMarketRepository extends MasterEntityRepository
{
    
}