Coramer\Sigtec\CompanyBundle\Entity\Plant:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            groups: [id,list,companies]
        name:
            expose: true
            groups: [list,companies,report_technical]
        email:
            expose: true
            groups: [list,companies]
        phones:
            expose: true
            groups: [companies]
        dedications:
            expose: true
            groups: [companies,report_technical]
        address:
            expose: true
            groups: [list,companies]
        createdAt:
            expose: true
            groups: [list,companies]
        updatedAt:
            expose: true
            groups: [list,companies]