Coramer\Sigtec\CompanyBundle\Entity\Dedication:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            groups: [id,list,companies]
        description:
            expose: true
            groups: [list,companies,report_technical]
        active:
            expose: true
            groups: [list]
        createdAt:
            expose: true
            groups: [list]
        updatedAt:
            expose: true
            groups: [list]