Coramer\Sigtec\CompanyBundle\Entity\Company:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            groups: [list,id]
        name:
            expose: true
            groups: [list,report_technical]
        rif:
            expose: true
            groups: [list,report_technical]
        rifValidated:
            expose: true
            groups: [list]
        status:
            expose: true
            groups: [list]
        createdAt:
            expose: true
            groups: [list]
        updatedAt:
            expose: true
            groups: [list]
        activeBusiness:
            expose: true
            groups: [list]
        lastTechnicalReportDateCreated:
            expose: true
            groups: [list]