<?php

namespace Coramer\Sigtec\CompanyBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Coramer\Sigtec\CoreBundle\Repository\Model\MasterEntityRepository;
/**
 * Repositorio de dedicaciones
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DedicationRepository extends MasterEntityRepository
{
}
