<?php


namespace Coramer\Sigtec\CompanyBundle\Repository;

use Tecnocreaciones\Bundle\ResourceBundle\Doctrine\ORM\EntityRepository;

/**
 * PlantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlantRepository extends EntityRepository
{   
    function findByCompanyNameAndUser(array $parameters)
    {
        $name = null;
        if(isset($parameters['name'])){
            $name = $parameters['name'];
        }
        $qb = $this->createQueryBuilder('p');
        $qb
                ->select('p')
                ->andWhere('p.name = :name')
                ->innerJoin('p.company', 'c')
                ->innerJoin('c.user', 'u')
                ->andWhere('u.id = :user')
                ->setParameters(array(
                    'name' => $name,
                    'user' => $this->getUser(),
                ))
                ;
        return $qb->getQuery()->getResult();
    }
}
