coramer_sigtec_backend_company_report_technical_properties_growth_potential_other_market:
    pattern: /.{_format}
    defaults:
        _controller: coramer_sigtec_backend.controller.company_report_technical_properties_growth_potential_other_market:listAction
        _format: json
    options:
        expose: true
    requirements:
        _method: GET
        _format: json|xml
        
coramer_sigtec_backend_company_report_technical_properties_growth_potential_other_market_form:
    pattern: /get-form
    defaults:
        _controller: coramer_sigtec_backend.controller.company_report_technical_properties_growth_potential_other_market:getFormAction
        _format: html
        _sylius:
            form: coramer_sigtec_reporttechnicalbundle_properties_growthpotential_othermarket
    options:
        expose: true
    requirements:
        _method: GET
        _format: html
        
coramer_sigtec_backend_company_report_technical_properties_growth_potential_other_market_create:
    pattern: /create
    defaults:
        _controller: coramer_sigtec_backend.controller.company_report_technical_properties_growth_potential_other_market:createAction
        _format: json
        _sylius:
            form: coramer_sigtec_reporttechnicalbundle_properties_growthpotential_othermarket
    options:
        expose: true
    requirements:
        _method: POST|PUT
        _format: json|xml
        
coramer_sigtec_backend_company_report_technical_properties_growth_potential_other_market_update:
    pattern: /{slug}/update
    defaults:
        _controller: coramer_sigtec_backend.controller.company_report_technical_properties_growth_potential_other_market:updateAction
        _format: json
        _sylius:
            form: coramer_sigtec_reporttechnicalbundle_properties_growthpotential_othermarket
    options:
        expose: true
    requirements:
        _method: POST|PUT
        _format: json|xml
        
coramer_sigtec_backend_company_report_technical_properties_growth_potential_other_market_delete:
    pattern:  /{slug}/delete
    defaults:
        _controller: coramer_sigtec_backend.controller.company_report_technical_properties_growth_potential_other_market:deleteAction
        _format: json
    options:
        expose: true
    requirements:
        _method: POST|DELETE
        _format: json|xml