coramer_sigtec_backend_company_report_technical_detail_product_storage_material:
    pattern: /materials.{_format}
    defaults:
        _controller: coramer_sigtec_backend.controller.company_report_technical_properties_material:getActiveAction
        _format: json
    options:
        expose: true
    requirements:
        _method: GET
        _format: json|xml