<?php

namespace Coramer\Sigtec\ReportTechnicalBundle\Repository\Properties\DescriptionAreaCompany;

use Doctrine\ORM\EntityRepository;

/**
 * MaterialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MaterialRepository extends EntityRepository
{
}
