coramer_sigtec_web_company:
    resource: "@CoramerSigtecWebBundle/Resources/config/routing/backend/company/company.yml"
    prefix:   /
    
coramer_sigtec_company_plant:
    resource: "@CoramerSigtecWebBundle/Resources/config/routing/backend/company/plant.yml"
    prefix:   /plants
    
coramer_sigtec_company_contact:
    resource: "@CoramerSigtecWebBundle/Resources/config/routing/backend/company/contact.yml"
    prefix:   /contacts
    
coramer_sigtec_company_report_technical:
    resource: "@CoramerSigtecWebBundle/Resources/config/routing/backend/company/report_technical/report_technical.yml"
    prefix:   /report-technical