coramer_sigtec_web:
    resource: "@CoramerSigtecWebBundle/Resources/config/routing/backend/company/company.yml"
    prefix:   /
    
coramer_sigtec_company_plant:
    resource: "@CoramerSigtecWebBundle/Resources/config/routing/backend/company/plant.yml"
    prefix:   /plants
    
coramer_sigtec_company_contact:
    resource: "@CoramerSigtecWebBundle/Resources/config/routing/backend/company/contact.yml"
    prefix:   /contacts