coramer_sigtec_backend_company_plant_create:
    pattern:  /{company_id}/create
    defaults:
        _controller: coramer_sigtec_backend.controller.company_plant:newAction
        _sylius:
            form: coramer_sigtec_companybundle_plant
    requirements: { _method: GET|POST }
    
coramer_sigtec_backend_company_plant_show:
    pattern:  /{id}/show
    defaults:
        _controller: coramer_sigtec_backend.controller.company_plant:showAction
    requirements: { _method: GET }
    
coramer_sigtec_backend_company_plant_update:
    pattern:  /{id}/update
    defaults:
        _controller: coramer_sigtec_backend.controller.company_plant:updateAction
        _sylius:
            form: coramer_sigtec_companybundle_plant
    requirements: { _method: GET|PUT }
    
coramer_sigtec_backend_company_plant_delete:
    pattern:  /{id}/delete
    defaults:
        _controller: coramer_sigtec_backend.controller.company_plant:deleteAction
    requirements: { _method: POST|DELETE }
    
coramer_sigtec_backend_company_plant_company:
    pattern:  /{company_id}/plants.{_format}
    defaults:
        _controller: coramer_sigtec_backend.controller.company_plant:getPlantsOfCompanyAction
        _format: json
    options:
        expose: true
    requirements:
        _method: GET
        _format: json|xml