coramer_sigtec_company_plant_create:
    pattern:  /{company_id}/create
    defaults:
        _controller: coramer_sigtec.controller.company_plant:newAction
        _sylius:
            form: coramer_sigtec_companybundle_plant
    requirements: { _method: GET|POST }