coramer_sigtec_backend_company_index:
    pattern:  /.{_format}
    defaults:
        _controller:  coramer_sigtec_backend.controller.company:indexAction
        _format: html
    options:
        expose: true
    requirements: { _method: GET }