coramer_sigtec_backend_company_report_technical_index:
    pattern:  /.{_format}
    defaults:
        _controller: coramer_sigtec_backend.controller.company_report_technical:indexAction
        _format: html
    options:
        expose: true
    requirements:
        _method: GET