<?php

/*
 * This file is part of the TecnocreacionesVzlaEntityBundle package.
 * 
 * (c) www.tecnocreaciones.com.ve
 * 
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Tecnocreaciones\Vzla\EntityBundle\Repository;

/**
 * CityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CityRepository extends EntityRepository
{
    /**
     * 
     * @param \Tecnocreaciones\Vzla\EntityBundle\Entity\State $state
     * @return type
     */
    function getQueryByState($state) {
        $qb = $this->createQueryBuilder('c');
        if($state === null){
           $qb->setMaxResults(0);
           return $qb;
        }
        $qb
                ->andWhere('c.state = :state')
                ->setParameter('state', $state)
                ;
        return $state;
    }
}
