coramer_sigtec_backend_company_report_technical_properties_additive_used:
    pattern: /.{_format}
    defaults:
        _controller: coramer_sigtec_backend.controller.company_report_technical_properties_additive_used:listAction
        _format: json
    options:
        expose: true
    requirements:
        _method: GET
        _format: json|xml
        
coramer_sigtec_backend_company_report_technical_properties_additive_used_form:
    pattern:  /get-form
    defaults:
        _controller: coramer_sigtec_backend.controller.company_report_technical_properties_additive_used:getFormAction
        _sylius:
            form: coramer_sigtec_reporttechnicalbundle_properties_additiveused
    options:
        expose: true
    requirements:
        _method: GET
        
coramer_sigtec_backend_company_report_technical_properties_additive_used_create:
    pattern:  /create
    defaults:
        _controller: coramer_sigtec_backend.controller.company_report_technical_properties_additive_used:createAction
        _format: json
        _sylius:
            form: coramer_sigtec_reporttechnicalbundle_properties_additiveused
    options:
        expose: true
    requirements:
        _method: POST
        _format: json|xml
        
coramer_sigtec_backend_company_report_technical_properties_additive_used_update:
    pattern:  /{slug}/update
    defaults:
        _controller: coramer_sigtec_backend.controller.company_report_technical_properties_additive_used:updateAction
        _sylius:
            form: coramer_sigtec_reporttechnicalbundle_properties_additiveused
    options:
        expose: true
    requirements:
        _method: POST|PUT
        
coramer_sigtec_backend_company_report_technical_properties_additive_used_delete:
    pattern:  /{slug}/delete
    defaults:
        _controller: coramer_sigtec_backend.controller.company_report_technical_properties_additive_used:deleteAction
        _format: json
    options:
        expose: true
    requirements:
        _method: POST|DELETE
        _format: json|xml
        