coramer_sigtec_backend_company_report_technical_properties_description_market:
    pattern: /.{_format}
    defaults:
        _controller: coramer_sigtec_backend.controller.company_report_technical_properties_description_market:listAction
        _format: json
    options:
        expose: true
    requirements:
        _method: GET
        _format: json|xml
        
coramer_sigtec_backend_company_report_technical_properties_description_market_form:
    pattern:  /get-form
    defaults:
        _controller: coramer_sigtec_backend.controller.company_report_technical_properties_description_market:getFormAction
        _sylius:
            form: coramer_sigtec_reporttechnicalbundle_properties_descriptionmarket
    options:
        expose: true
    requirements:
        _method: GET
        
coramer_sigtec_backend_company_report_technical_properties_description_market_create:
    pattern:  /create
    defaults:
        _controller: coramer_sigtec_backend.controller.company_report_technical_properties_description_market:createAction
        _format: json
        _sylius:
            form: coramer_sigtec_reporttechnicalbundle_properties_descriptionmarket
    options:
        expose: true
    requirements:
        _method: POST
        _format: json|xml
        
coramer_sigtec_backend_company_report_technical_properties_description_market_update:
    pattern:  /{slug}/update
    defaults:
        _controller: coramer_sigtec_backend.controller.company_report_technical_properties_description_market:updateAction
        _sylius:
            form: coramer_sigtec_reporttechnicalbundle_properties_descriptionmarket
        _format: json
    options:
        expose: true
    requirements:
        _method: POST|PUT
        
coramer_sigtec_backend_company_report_technical_properties_description_market_delete:
    pattern:  /{slug}/delete
    defaults:
        _controller: coramer_sigtec_backend.controller.company_report_technical_properties_description_market:deleteAction
        _format: json
    options:
        expose: true
    requirements:
        _method: POST|DELETE
        _format: json|xml