coramer_sigtec_company_report_technical_properties_growth_potential:
    resource: "@CoramerSigtecWebBundle/Resources/config/routing/backend/company/report_technical/properties/growth_potential/growing_market.yml"
    prefix:   /growth-market