coramer_sigtec_backend_company_report_technical_properties_production_level:
    pattern: /.{_format}
    defaults:
        _controller: coramer_sigtec_backend.controller.company_report_technical_properties_production_level:listAction
        _format: json
    options:
        expose: true
    requirements:
        _method: GET
        _format: json|xml

coramer_sigtec_backend_company_report_technical_properties_production_level_create:
    pattern:  /create
    defaults:
        _controller: coramer_sigtec_backend.controller.company_report_technical_properties_production_level:createAction
        _format: json
        _sylius:
            form: coramer_sigtec_reporttechnicalbundle_properties_productionlevel
    options:
        expose: true
    requirements:
        _method: POST
        _format: json|xml

coramer_sigtec_backend_company_report_technical_properties_production_level_delete:
    pattern:  /{slug}/delete
    defaults:
        _controller: coramer_sigtec_backend.controller.company_report_technical_properties_production_level:deleteAction
        _format: json
    options:
        expose: true
    requirements:
        _method: POST|DELETE
        _format: json|xml
        
coramer_sigtec_backend_company_report_technical_properties_production_level_update:
    pattern:  /{slug}/update
    defaults:
        _controller: coramer_sigtec_backend.controller.company_report_technical_properties_production_level:updateAction
        _sylius:
            form: coramer_sigtec_reporttechnicalbundle_properties_productionlevel
    options:
        expose: true
    requirements:
        _method: POST|PUT

coramer_sigtec_backend_company_report_technical_properties_production_level_form:
    pattern:  /get-form
    defaults:
        _controller: coramer_sigtec_backend.controller.company_report_technical_properties_production_level:getFormAction
        _sylius:
            form: coramer_sigtec_reporttechnicalbundle_properties_productionlevel
    options:
        expose: true
    requirements:
        _method: GET